<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EasyLS</title>
    <link rel="stylesheet" href="css/foundation.min.css" />
    <link rel="stylesheet" href="css/app.css" />
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="row logincontainer">
      <div class="medium-5 large-6 columns ">
        <h1>EasyLS</h1><hr>
        <p class="light">Login with your username and password</p>
        <p class="light">admb.ga is a private link shorterner used by <a href="#">Adam Blunt</a></p><hr>
        <small>Name: Adam Blunt (admb.ga) | 49 Short Links | EasyLS v1.2 DevAlpha NodeJS Edition</small>
      </div>
      <div class="medium-7 large-6 columns leftborder loginbox">



            <label>Username
              <input type="text" placeholder="Username" tabindex=1 autofocus>
            </label>
 
      <label>Password
        <input type="password" placeholder="Password" tabindex=3>
      </label>
      <button href="#" type="submit" class="button large black expanded" tabindex=4>Login</button>

    </div>

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>
