<div class="row logincontainer">
      <div class="medium-5 large-6 columns ">
        <h1>EasyLS</h1><hr>
        <p class="light">Login with your username and password</p>
        <p class="light">admb.ga is a private link shorterner used by <a href="#">Adam Blunt</a></p><hr>
        <small>Name: {systemname} | {linkcount} Short Links | EasyLS v{version} NodeJS Edition</small>
      </div>
      <div class="medium-7 large-6 columns leftborder loginbox">
        <form action="/login" method="POST">

            <label>Username
              <input name="user" type="text" placeholder="Username" tabindex=1 autofocus>
            </label>

      <label>Password
        <input name="pass" type="password" placeholder="Password" tabindex=3>
      </label>
      <button href="#" type="submit" class="button large black expanded" tabindex=4>Login</button>
    </form>

    </div>
