<li><a href="/admin/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a></li>
<li><a href="/admin/addshortlink"><i class="fa fa-fw fa-plus-circle"></i> Add Shortlink</a></li>
<li><a href="/admin/shortlinks/1"><i class="fa fa-fw fa-database"></i> Shortlinks</a></li>
<li><a href="/admin/configure/"><i class="fa fa-fw fa-cog"></i> Configure</a></li>
<li><a href="/admin/about/"><i class="fa fa-fw fa-question"></i> About</a></li>